### ISSUE TITLE
Are those detections in version V1.6.16.509 fasle?

### ISSUE THREAD

**Issue by Gitphex** [RNoeldner/CSVQuickViewer#14]
I downloaded CSVQuickViewer.exe version V1.6.16.509, so then i uploaded to Virustotal and i had the next result:

https://www.virustotal.com/gui/file/36c79e5002a2ed06e347f505cb97580e1b025d4e39959325deff9f513339bb89

Are those false positive?... How can i check the hash of the releases here in Github?

After uploading the file in Virustotal the hash for that file is 36c79e5002a2ed06e347f505cb97580e1b025d4e39959325deff9f513339bb89, can anyone please check and tell me if it's the same hash as the original file, since is very weird because when i check the same file before downloading it, pasting the url directly to the same file but from Github it appears clean, so i have the suspicion that maybe the file is infected after downloading the file, but i checked and my pc is clean.

Thanks in advance. Greetings.

**Comment by RNoeldner** [comment]
I am sorry to hear that some software that should protect your PC do recognize the software are malware, I believe it could be due to the fact that a lot of libraries are embedded into the executable for simplicity of the install.
I will add a version that does not do this but instead uses all DLL separately.
I can add a hash to the executable to make sure that what you download is what I did publish, but I do not know how that does helps this is information is from the same source (me). So if the software was actual malware not much is improved.

**Comment by RNoeldner** [comment]
Please try the new release, I hope virus detection is not irritated as much with the used libraries not being embedded into the main executable  any more. Now it can scan each dll separate  for possible risks.
In addition I have added MD5 checksums for all published installation methods, so you can be sure the files have not been tampered with.
