### ISSUE TITLE
V1.6.24.531 contains Wacatac trojan

### ISSUE THREAD

**Issue by JoelCanteroGCO** [RNoeldner/CSVQuickViewer#15]
I have tried to install the last version, 1.6.24.531 (that actually is on Pre-release), but when I execute it, Windows Defender detects a trojan called Wacatac in the executable file:

![image](https://user-images.githubusercontent.com/88024807/177104463-708f0549-fceb-43ff-bbd5-e4af39e211ed.png)
 
That's strange...

**Comment by RNoeldner** [comment]
Thank you for letting me know. I am afraid I can not do much I can assure you this trojan is not intentional part of the executable.

I could not spot the malware in my environment, I always hoped it is well protected but you never know. 

I use Library that does combine all dlls and executables into a single executable, this might raise suspicion with some virus checks.  I have added a distribution version that does not do so: all libraries are seperate, this makes checking them easier but the folder doe not look as clean with the clutter.
