### ISSUE TITLE
Copying cell content

### ISSUE THREAD

**Issue by charles-halifax** [RNoeldner/CSVQuickViewer#20]
What happens

Ctrl + Click multiple cells and clicking copy doesn't do anything.

What should happen

Selecting multiple cells (Ctrl + Click) and clicking copy should copy their content to the clipboard.

I'm using v1.7.2.567 on Windows 10 (most recent version). Thanks.

**Comment by RNoeldner** [comment]
This is expected behavior, a selection will select, if you want to copy use Ctrl-C or the context menu  (right mouse button)
Only the selected Cells will be copied. If nothing is selected the current cell content will be copied, if multiple columns are selected, you will get a table with header row.
You will find two different clipboard contends, one is HTML for copy into Excel or Word with formatting, one is Text only, then its tab delimited.
